<script setup>
import { onMounted, ref } from "vue";
import { LoaderCircle, MessageCircle, RefreshCw } from "lucide-vue-next";
import { api } from "../api/client";
const sessions = ref([]); const selected = ref(null); const loading = ref(true); const error = ref("");
async function load() { loading.value = true; try { const data = await api.get("/admin/child_chat_sessions", "admin"); sessions.value = Array.isArray(data) ? data : []; selected.value = sessions.value[0] || null; } catch (cause) { error.value = cause.message || "聊天记录加载失败"; } finally { loading.value = false; } }
onMounted(load);
</script>
<template><div><div class="page-heading"><div><span class="mono-label">ADMIN / COMPANION LOGS</span><h1>儿童聊天记录</h1><p>查看儿童端与 AI 陪伴老师的历史对话。</p></div><button class="button button-dark" @click="load"><RefreshCw :size="15" />刷新</button></div><div v-if="error" class="notice error">{{ error }}</div><div v-if="loading" class="empty-state"><LoaderCircle class="spin" :size="28" /></div><div v-else class="data-grid" style="grid-template-columns:300px minmax(0,1fr); margin-top:18px"><section class="surface surface-pad"><div class="surface-title"><h2>对话列表</h2><span>{{ sessions.length }} SESSIONS</span></div><div v-if="!sessions.length" class="empty-state"><MessageCircle :size="26" style="margin-bottom:8px; color:var(--cyan)" /><strong>暂无儿童聊天记录</strong><span>孩子开始对话后会出现在这里。</span></div><div v-else style="display:grid; gap:7px"><button v-for="session in sessions" :key="session.id" class="button button-light" :class="{ 'button-primary': selected?.id === session.id }" style="justify-content:flex-start; text-align:left" @click="selected=session"><span><strong style="display:block">{{ session.student_name || '未知学生' }}</strong><small class="session-source" style="display:block; margin-top:4px">{{ session.source === 'device' ? `小智设备${session.device_id ? ` · ${session.device_id}` : ''}` : '儿童网页' }}</small><small style="display:block; margin-top:4px; opacity:.7">{{ session.parent_name || '未知家长' }} · {{ session.title || '儿童陪伴对话' }}</small></span></button></div></section><section class="surface surface-pad"><div class="surface-title"><h2>对话内容</h2><span>{{ selected?.messages?.length || 0 }} MESSAGES</span></div><div v-if="!selected" class="empty-state">请选择一个对话。</div><div v-else style="display:grid; gap:10px"><article v-for="item in selected.messages || []" :key="item.id" class="chat-bubble" :class="{ user: item.role === 'user' }"><small style="display:block; margin-bottom:5px; opacity:.65">{{ item.role === 'user' ? '孩子' : 'AI 陪伴老师' }} · {{ item.created_at ? new Date(item.created_at).toLocaleString('zh-CN') : '' }}</small>{{ item.content }}</article></div></section></div></div></template>
<style scoped>.spin { animation: spin 1s linear infinite; } @keyframes spin { to { transform:rotate(360deg); } }</style>
