<script setup>
import { computed, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { CalendarCheck, FileText, LoaderCircle, Sprout, UserRound } from "lucide-vue-next";
import { api } from "../api/client";
const id = String(useRoute().params.id); const kid = ref(null); const disciplines = ref([]); const attendances = ref([]); const error = ref("");
const presentCount = computed(() => attendances.value.filter((item) => item.status === "Present").length); const absentCount = computed(() => attendances.value.filter((item) => item.status === "Absent").length); const name = computed(() => [kid.value?.first_name, kid.value?.second_name, kid.value?.surname].filter(Boolean).join(" "));
onMounted(async () => { try { const [student, disciplineData, attendanceData] = await Promise.all([api.get(`/students/${id}`, "parent"), api.get(`/disciplines?student_id=${id}`, "parent"), api.get(`/attendances?student_id=${id}`, "parent")]); kid.value = student; disciplines.value = Array.isArray(disciplineData) ? disciplineData : []; attendances.value = Array.isArray(attendanceData) ? attendanceData : []; } catch (cause) { error.value = cause.message || "没有权限查看该孩子，或孩子不存在。"; } });
</script>
<template><div><div class="page-heading"><div><span class="mono-label">CHILD / PROFILE</span><h1>{{ name || '孩子详情' }}</h1><p>查看孩子在园所的出勤和纪律记录。</p></div><RouterLink class="button button-light" to="/parent_dashboard/my_kids">返回孩子列表</RouterLink></div><div v-if="error" class="notice error">{{ error }}</div><div v-else-if="!kid" class="empty-state"><LoaderCircle class="spin" :size="28" /></div><template v-else><div class="metric-grid"><div class="metric-card"><small>学号</small><div class="metric-value" style="font-size:24px">{{ kid.admission_number }}</div><div class="metric-foot"><span>学号</span><UserRound :size="14" /></div></div><div class="metric-card"><small>班级</small><div class="metric-value" style="font-size:24px">{{ kid.classroom?.name || '-' }}</div><div class="metric-foot"><span>班级</span><UserRound :size="14" /></div></div><div class="metric-card"><small>出勤 / 缺勤</small><div class="metric-value" style="font-size:24px">{{ presentCount }} / {{ absentCount }}</div><div class="metric-foot"><span>考勤</span><CalendarCheck :size="14" /></div></div><div class="metric-card"><small>纪律记录</small><div class="metric-value" style="font-size:24px">{{ disciplines.length }}</div><div class="metric-foot"><span>记录</span><FileText :size="14" /></div></div></div><section class="surface surface-pad" style="margin-top:18px"><div class="surface-title"><h2>学生描述</h2><span>档案信息</span></div><p style="margin:0; color:#5d7887; line-height:1.8; font-size:13px">{{ kid.description || '暂无描述' }}</p><div style="margin-top:18px"><RouterLink class="button button-primary" :to="`/parent_dashboard/my_kids/${kid.id}/growth`"><Sprout :size="15" />成长记录</RouterLink></div></section><div class="data-grid" style="margin-top:18px"><section class="surface"><div class="surface-title" style="padding:18px 18px 0"><h2>考勤明细</h2><span>{{ attendances.length }} 条记录</span></div><div v-if="!attendances.length" class="empty-state">暂无考勤记录</div><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>日期</th><th>状态</th></tr></thead><tbody><tr v-for="item in attendances" :key="item.id"><td>{{ item.date }}</td><td><span class="status" :class="item.status === 'Present' ? 'ok' : 'warn'">{{ item.status === 'Present' ? '出勤' : '缺勤' }}</span></td></tr></tbody></table></div></section><section class="surface"><div class="surface-title" style="padding:18px 18px 0"><h2>纪律明细</h2><span>{{ disciplines.length }} 条记录</span></div><div v-if="!disciplines.length" class="empty-state">暂无纪律记录</div><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>标题</th><th>日期</th></tr></thead><tbody><tr v-for="item in disciplines" :key="item.id"><td>{{ item.title }}</td><td>{{ item.date }}</td></tr></tbody></table></div></section></div></template></div></template>
<style scoped>.spin { animation: spin 1s linear infinite; } @keyframes spin { to { transform:rotate(360deg); } }</style>
