<script setup>
import { onMounted, ref } from "vue";
import { ArrowLeft, FileText, LoaderCircle, Plus, Sprout } from "lucide-vue-next";
import { useRoute, useRouter } from "vue-router";
import { api } from "../api/client";
const route = useRoute(); const router = useRouter(); const student = ref(null); const error = ref("");
onMounted(async () => { try { student.value = await api.get(`/students/${route.params.id}`, "teacher"); } catch (cause) { error.value = cause.message || "学生信息加载失败"; } });
</script>
<template><div><div class="page-heading"><div><span class="mono-label">班级 / STUDENT PROFILE</span><h1>{{ student ? `${student.first_name || ''} ${student.second_name || ''} ${student.surname || ''}` : '学生详情' }}</h1><p>查看学生基础信息，并从这里记录需要关注的事项。</p></div><button class="button button-light" @click="router.back()"><ArrowLeft :size="15" />返回</button></div><div v-if="error" class="notice error">{{ error }}</div><div v-else-if="!student" class="empty-state"><LoaderCircle class="spin" :size="28" /></div><template v-else><div class="metric-grid"><div class="metric-card"><small>学号</small><div class="metric-value" style="font-size:24px">{{ student.admission_number }}</div></div><div class="metric-card"><small>年龄</small><div class="metric-value" style="font-size:24px">{{ student.age }}</div></div><div class="metric-card"><small>班级</small><div class="metric-value" style="font-size:24px">{{ student.classroom?.name || '-' }}</div></div><div class="metric-card"><small>家长</small><div class="metric-value" style="font-size:24px">{{ student.parents?.length || 0 }}</div></div></div><section class="surface surface-pad" style="margin-top:18px"><div class="surface-title"><h2><FileText :size="16" style="vertical-align:-3px; margin-right:6px" />学生描述</h2><span>档案信息</span></div><p style="margin:0; color:var(--muted-dark); line-height:1.8">{{ student.description || '暂无描述' }}</p><div style="margin-top:18px; display:flex; gap:10px; flex-wrap:wrap"><button class="button button-primary" type="button" @click="router.push(`/dashboard/kids_list/${student.id}/growth`)"><Sprout :size="15" />成长记录</button><button class="button button-light" type="button" @click="router.push({ path: '/dashboard/addcase', query: { student_id: student.id } })"><Plus :size="15" />添加纪律记录</button></div></section></template></div></template>
<style scoped>.spin { animation: spin 1s linear infinite; } @keyframes spin { to { transform:rotate(360deg); } }</style>
